### ISSUE TITLE
Cannot enable autopilot.

### ISSUE THREAD

**Issue by Thauyel** [ItsAlphaNeon/AutoPilot-for-BetterDiscord#1]
![Screenshot_1](https://github.com/ItsAlphaNeon/AutoPilot-for-BetterDiscord/assets/47196768/2b7445f0-071c-466e-8d3a-5e50aaa76f8d)
im getting this error when i try to enable it. so i cannot use it rn. can you please help me. ty

**Comment by ItsAlphaNeon** [comment]
![image](https://github.com/ItsAlphaNeon/AutoPilot-for-BetterDiscord/assets/102443376/119dde28-a26f-4937-aefd-f2e3272c719d)

Hello, you must click enable in each channel you want to enable first!

Remember to add your key in settings first!

**Comment by Thauyel** [comment]
Ohh! Okay now i feel dumb. Thanks again for the help. Great plugin!

**Comment by Thauyel** [comment]
![Screenshot_1](https://github.com/ItsAlphaNeon/AutoPilot-for-BetterDiscord/assets/47196768/9eb2b07c-f76b-4208-8df5-16850d91ed79)
Hello, again now im receiving this error and i dont know how to deal with that. I did put my api key in, in the settings. Sorry for taking your time.

**Comment by Thauyel** [comment]
Okay i fixed that with using a VPN.

**Comment by ItsAlphaNeon** [comment]
you're good, enjoy the plugin!
