### ISSUE TITLE
I get error while trying to use the plugin.

### ISSUE THREAD

**Issue by Thauyel** [ItsAlphaNeon/AutoPilot-for-BetterDiscord#2]
Hello! So I have tried using it again but when i click the button to enable autopilot. It gives multiple errors. I am adding the screenshots below. Can you help me again please?
![Screenshot_2](https://github.com/ItsAlphaNeon/AutoPilot-for-BetterDiscord/assets/47196768/eccc3e0d-3fee-4178-8b2f-3a6ff725a812)
![Screenshot_3](https://github.com/ItsAlphaNeon/AutoPilot-for-BetterDiscord/assets/47196768/2424b6bc-ca18-48e8-9b80-5ab72d8ec571)
Thank you!

**Comment by ItsAlphaNeon** [comment]
Hello, this usually indicates that you either have sent too many requests, or that OpenAI is blocking you for some reason. 

Most likely is that you've used your free API quota

![image](https://github.com/ItsAlphaNeon/AutoPilot-for-BetterDiscord/assets/102443376/d7ff81c0-89c9-4613-a5c7-1ffc30b16f0c)

**Comment by Thauyel** [comment]
Oh. Okay Thank you!
