### ISSUE TITLE
Prob a dumb question

### ISSUE THREAD

**Issue by iGetUploaded** [ItsAlphaNeon/AutoPilot-for-BetterDiscord#3]
Is it supposed to start right away and msg ppl or do u need to tweak some stuff before it does?

**Comment by ItsAlphaNeon** [comment]
Once you add your key and enable a channel, you must turn on the autopilot by clicking the button at the bottom

![image](https://github.com/ItsAlphaNeon/AutoPilot-for-BetterDiscord/assets/102443376/17f11f6a-dbb0-4b34-8848-e55a2ec2da4f)

There is also a bug where if a conversation is too short ~ <10-15 messages, it wont generate properly.

Let me know if you're still having issues

**Comment by iGetUploaded** [comment]
Hey just figured tht out & now i'm getting 429 rate limit

**Comment by ItsAlphaNeon** [comment]
error 429 likely means you're either sending too many requests, or that your trial / limit has been exceeded.

double check to make sure you can call your API, as you might not be able to.

**Comment by iGetUploaded** [comment]
How would I go about checking to see if I can all my API

**Comment by ItsAlphaNeon** [comment]
Try this site:
[BetterChatGPT](https://bettergpt.chat/)

If you can get responses here, you can call your API key

**Comment by iGetUploaded** [comment]
![image](https://github.com/ItsAlphaNeon/AutoPilot-for-BetterDiscord/assets/54633753/174b4437-8ba6-4961-92b9-c535a15aa026)
 generated a new api key too and its showing this

**Comment by ItsAlphaNeon** [comment]
Assuming you're using the trial, you've exceeded your limits. 

You will need to link a payment method in order to use the API from this point onwards, as your trial API usage is over.

**Comment by iGetUploaded** [comment]
oh alrighty thanks for the help man
