### ISSUE TITLE
where is the button?

### ISSUE THREAD

**Issue by FarikLoL** [ItsAlphaNeon/AutoPilot-for-BetterDiscord#5]
where is the button?
![image](https://github.com/ItsAlphaNeon/AutoPilot-for-BetterDiscord/assets/46515364/e1bea80a-57b1-4643-9b8a-baf5cefb8fb5)

**Comment by ItsAlphaNeon** [comment]
It looks like Discord updated and broke the plugin. This will take a little time to fix. Thank you for your patience

**Comment by ItsAlphaNeon** [comment]
This issue is now fixed, I apologize for not finding this issue sooner, as it seems to be a Windows only bug, and my development environment was in Linux. Please let me know if there are any other issues you are facing

**Comment by PortalRex** [comment]
Problem has returned, both on windows and linux (popOS)
